# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Add key mongodb
    apt_key:
      id: "EA312927"
      keyserver: "hkp://keyserver.ubuntu.com:80"
      state: present
  - name: Add mongodb repo
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
      state: present
  - name: Install mongodb package 
    apt:
      name: "mongodb-org"
      update_cache: yes
      state: present
  - name: enable service mongod
    systemd:
      name: mongod
      enabled: yes
      state: started
    #debug:
    #  msg: "В этом сценарии нужно добавить модули для установки mongodb, после можно удалить вызов модуля debug, который выводит это сообщение"

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: all
  gather_facts: no

  tasks:
  - name: Get application code
    git:
     repo: 'https://github.com/Artemmkin/reddit.git'
     dest: ~/reddit
  - name: Install app libs
    bundler:
      state: present
      deployment_mode: yes  
      chdir: ~/reddit
  - name: Start app service
    systemd:
      name: puma
      enabled: yes
      state: started     
      user: yes
